# Generated by Django 3.2.7 on 2021-09-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btclabw', '0002_auto_20210919_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeOrder',
            new_name='UserOrder',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='created_on',
            new_name='member_since',
        ),
        migrations.AddField(
            model_name='membership',
            name='valid_thru',
            field=models.DateField(null=True, verbose_name='End of service date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_contact',
            field=models.DateTimeField(null=True, verbose_name='Last date user was contacted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_to_telegram',
            field=models.BooleanField(default=True, verbose_name='Whether or not to notify to Telegram'),
        ),
    ]
